name: grocery_app
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ^3.7.0
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.7.2
  cupertino_icons: ^1.0.5
  connectivity_plus: ^6.1.4
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^2.1.0
  google_sign_in: ^6.3.0
  flutter_login_facebook: ^1.1.0
  http: ^1.4.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  flutter_facebook_auth: ^7.1.2
  permission_handler: ^12.0.0+1
  file_picker: ^10.1.9
  firebase_messaging: ^15.2.1
  flutter_local_notifications: ^18.0.1
  firebase_analytics: ^11.4.1
  logger: ^2.3.0


dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/MontserratRomanBold.ttf
          weight: 700
        - asset: assets/fonts/MontserratSemiBold.ttf
          weight: 600
        - asset: assets/fonts/MontserratRegular.ttf
          weight: 400
        - asset: assets/fonts/MontserratBold.ttf
          weight: 700
        - asset: assets/fonts/MontserratMedium.ttf
          weight: 500
        - asset: assets/fonts/MontserratLight.ttf
          weight: 300
